// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: payload.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dwango.nicolive.chat.service.edge
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ChunkedMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Meta meta { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::dwango.nicolive.chat.data.NicoliveMessage message
        {
            get => __pbn__payload.Is(2) ? ((global::dwango.nicolive.chat.data.NicoliveMessage)__pbn__payload.Object) : default;
            set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
        }
        public bool ShouldSerializemessage() => __pbn__payload.Is(2);
        public void Resetmessage() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__payload, 2);

        private global::ProtoBuf.DiscriminatedUnion32Object __pbn__payload;

        [global::ProtoBuf.ProtoMember(4)]
        public global::dwango.nicolive.chat.data.NicoliveState state
        {
            get => __pbn__payload.Is(4) ? ((global::dwango.nicolive.chat.data.NicoliveState)__pbn__payload.Object) : default;
            set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnion32Object(4, value);
        }
        public bool ShouldSerializestate() => __pbn__payload.Is(4);
        public void Resetstate() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__payload, 4);

        [global::ProtoBuf.ProtoMember(5)]
        public Signal signal
        {
            get => __pbn__payload.Is(5) ? ((Signal)__pbn__payload.Int32) : default;
            set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnion32Object(5, (int)value);
        }
        public bool ShouldSerializesignal() => __pbn__payload.Is(5);
        public void Resetsignal() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__payload, 5);

        [global::ProtoBuf.ProtoContract()]
        public partial class Meta : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string id { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
            public global::System.DateTime? at { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            public global::dwango.nicolive.chat.data.NicoliveOrigin origin { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Signal
        {
            Flushed = 0,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PackedSegment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<ChunkedMessage> messages { get; } = new global::System.Collections.Generic.List<ChunkedMessage>();

        [global::ProtoBuf.ProtoMember(2)]
        public Next next { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public StateSnapshot snapshot { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Next : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string uri { get; set; } = "";

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class StateSnapshot : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string uri { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChunkedEntry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        public BackwardSegment backward
        {
            get => __pbn__entry.Is(2) ? ((BackwardSegment)__pbn__entry.Object) : default;
            set => __pbn__entry = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializebackward() => __pbn__entry.Is(2);
        public void Resetbackward() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entry, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__entry;

        [global::ProtoBuf.ProtoMember(3)]
        public MessageSegment previous
        {
            get => __pbn__entry.Is(3) ? ((MessageSegment)__pbn__entry.Object) : default;
            set => __pbn__entry = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeprevious() => __pbn__entry.Is(3);
        public void Resetprevious() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entry, 3);

        [global::ProtoBuf.ProtoMember(1)]
        public MessageSegment segment
        {
            get => __pbn__entry.Is(1) ? ((MessageSegment)__pbn__entry.Object) : default;
            set => __pbn__entry = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializesegment() => __pbn__entry.Is(1);
        public void Resetsegment() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entry, 1);

        [global::ProtoBuf.ProtoMember(4)]
        public ReadyForNext next
        {
            get => __pbn__entry.Is(4) ? ((ReadyForNext)__pbn__entry.Object) : default;
            set => __pbn__entry = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializenext() => __pbn__entry.Is(4);
        public void Resetnext() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entry, 4);

        [global::ProtoBuf.ProtoContract()]
        public partial class ReadyForNext : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public long at { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MessageSegment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? from { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? until { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string uri { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BackwardSegment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? until { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PackedSegment.Next segment { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public PackedSegment.StateSnapshot snapshot { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
