// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: struct.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Google.Protobuf.WellKnownTypes
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Struct : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, Value> fields { get; } = new global::System.Collections.Generic.Dictionary<string, Value>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Value : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NullValue null_value
        {
            get => __pbn__kind.Is(1) ? ((NullValue)__pbn__kind.Int32) : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(1, (int)value);
        }
        public bool ShouldSerializenull_value() => __pbn__kind.Is(1);
        public void Resetnull_value() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 1);

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__kind;

        [global::ProtoBuf.ProtoMember(2)]
        public double number_value
        {
            get => __pbn__kind.Is(2) ? __pbn__kind.Double : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializenumber_value() => __pbn__kind.Is(2);
        public void Resetnumber_value() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 2);

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string string_value
        {
            get => __pbn__kind.Is(3) ? ((string)__pbn__kind.Object) : "";
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(3, value);
        }
        public bool ShouldSerializestring_value() => __pbn__kind.Is(3);
        public void Resetstring_value() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 3);

        [global::ProtoBuf.ProtoMember(4)]
        public bool bool_value
        {
            get => __pbn__kind.Is(4) ? __pbn__kind.Boolean : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(4, value);
        }
        public bool ShouldSerializebool_value() => __pbn__kind.Is(4);
        public void Resetbool_value() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 4);

        [global::ProtoBuf.ProtoMember(5)]
        public Struct struct_value
        {
            get => __pbn__kind.Is(5) ? ((Struct)__pbn__kind.Object) : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(5, value);
        }
        public bool ShouldSerializestruct_value() => __pbn__kind.Is(5);
        public void Resetstruct_value() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 5);

        [global::ProtoBuf.ProtoMember(6)]
        public ListValue list_value
        {
            get => __pbn__kind.Is(6) ? ((ListValue)__pbn__kind.Object) : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(6, value);
        }
        public bool ShouldSerializelist_value() => __pbn__kind.Is(6);
        public void Resetlist_value() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 6);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Value> values { get; } = new global::System.Collections.Generic.List<Value>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum NullValue
    {
        NULL_VALUE = 0,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
