// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: atoms.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dwango.nicolive.chat.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Chat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int vpos { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public AccountStatus account_status { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get => __pbn__name ?? "";
            set => __pbn__name = value;
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(5)]
        public long raw_user_id
        {
            get => __pbn__raw_user_id.GetValueOrDefault();
            set => __pbn__raw_user_id = value;
        }
        public bool ShouldSerializeraw_user_id() => __pbn__raw_user_id != null;
        public void Resetraw_user_id() => __pbn__raw_user_id = null;
        private long? __pbn__raw_user_id;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string hashed_user_id
        {
            get => __pbn__hashed_user_id ?? "";
            set => __pbn__hashed_user_id = value;
        }
        public bool ShouldSerializehashed_user_id() => __pbn__hashed_user_id != null;
        public void Resethashed_user_id() => __pbn__hashed_user_id = null;
        private string __pbn__hashed_user_id;

        [global::ProtoBuf.ProtoMember(7)]
        public Modifier modifier { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int no { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Modifier : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public Pos position { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public Size size { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            public ColorName named_color
            {
                get => __pbn__color.Is(3) ? ((ColorName)__pbn__color.Int32) : default;
                set => __pbn__color = new global::ProtoBuf.DiscriminatedUnion32Object(3, (int)value);
            }
            public bool ShouldSerializenamed_color() => __pbn__color.Is(3);
            public void Resetnamed_color() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__color, 3);

            private global::ProtoBuf.DiscriminatedUnion32Object __pbn__color;

            [global::ProtoBuf.ProtoMember(4)]
            public FullColor full_color
            {
                get => __pbn__color.Is(4) ? ((FullColor)__pbn__color.Object) : default;
                set => __pbn__color = new global::ProtoBuf.DiscriminatedUnion32Object(4, value);
            }
            public bool ShouldSerializefull_color() => __pbn__color.Is(4);
            public void Resetfull_color() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__color, 4);

            [global::ProtoBuf.ProtoMember(5)]
            public Font font { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            public Opacity opacity { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class FullColor : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                public int r { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                public int g { get; set; }

                [global::ProtoBuf.ProtoMember(3)]
                public int b { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public enum Pos
            {
                naka = 0,
                shita = 1,
                ue = 2,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum Size
            {
                medium = 0,
                small = 1,
                big = 2,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum ColorName
            {
                white = 0,
                red = 1,
                pink = 2,
                orange = 3,
                yellow = 4,
                green = 5,
                cyan = 6,
                blue = 7,
                purple = 8,
                black = 9,
                white2 = 10,
                red2 = 11,
                pink2 = 12,
                orange2 = 13,
                yellow2 = 14,
                green2 = 15,
                cyan2 = 16,
                blue2 = 17,
                purple2 = 18,
                black2 = 19,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum Font
            {
                defont = 0,
                mincho = 1,
                gothic = 2,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum Opacity
            {
                Normal = 0,
                Translucent = 1,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum AccountStatus
        {
            Standard = 0,
            Premium = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperatorComment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get => __pbn__name ?? "";
            set => __pbn__name = value;
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(3)]
        public Chat.Modifier modifier { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string link
        {
            get => __pbn__link ?? "";
            set => __pbn__link = value;
        }
        public bool ShouldSerializelink() => __pbn__link != null;
        public void Resetlink() => __pbn__link = null;
        private string __pbn__link;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Jump : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? wait { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Redirect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string uri { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? wait { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimpleNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ichiba
        {
            get => __pbn__message.Is(1) ? ((string)__pbn__message.Object) : "";
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeichiba() => __pbn__message.Is(1);
        public void Resetichiba() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__message;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string quote
        {
            get => __pbn__message.Is(2) ? ((string)__pbn__message.Object) : "";
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializequote() => __pbn__message.Is(2);
        public void Resetquote() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 2);

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string emotion
        {
            get => __pbn__message.Is(3) ? ((string)__pbn__message.Object) : "";
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeemotion() => __pbn__message.Is(3);
        public void Resetemotion() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 3);

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string cruise
        {
            get => __pbn__message.Is(4) ? ((string)__pbn__message.Object) : "";
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializecruise() => __pbn__message.Is(4);
        public void Resetcruise() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 4);

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string program_extended
        {
            get => __pbn__message.Is(5) ? ((string)__pbn__message.Object) : "";
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeprogram_extended() => __pbn__message.Is(5);
        public void Resetprogram_extended() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 5);

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ranking_in
        {
            get => __pbn__message.Is(6) ? ((string)__pbn__message.Object) : "";
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeranking_in() => __pbn__message.Is(6);
        public void Resetranking_in() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 6);

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ranking_updated
        {
            get => __pbn__message.Is(8) ? ((string)__pbn__message.Object) : "";
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
        }
        public bool ShouldSerializeranking_updated() => __pbn__message.Is(8);
        public void Resetranking_updated() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 8);

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string visited
        {
            get => __pbn__message.Is(7) ? ((string)__pbn__message.Object) : "";
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializevisited() => __pbn__message.Is(7);
        public void Resetvisited() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 7);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Gift : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string item_id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public long advertiser_user_id
        {
            get => __pbn__advertiser_user_id.GetValueOrDefault();
            set => __pbn__advertiser_user_id = value;
        }
        public bool ShouldSerializeadvertiser_user_id() => __pbn__advertiser_user_id != null;
        public void Resetadvertiser_user_id() => __pbn__advertiser_user_id = null;
        private long? __pbn__advertiser_user_id;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string advertiser_name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public long point { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string item_name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public int contribution_rank
        {
            get => __pbn__contribution_rank.GetValueOrDefault();
            set => __pbn__contribution_rank = value;
        }
        public bool ShouldSerializecontribution_rank() => __pbn__contribution_rank != null;
        public void Resetcontribution_rank() => __pbn__contribution_rank = null;
        private int? __pbn__contribution_rank;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Nicoad : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public V0 v0
        {
            get => __pbn__versions.Is(1) ? ((V0)__pbn__versions.Object) : default;
            set => __pbn__versions = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializev0() => __pbn__versions.Is(1);
        public void Resetv0() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__versions, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__versions;

        [global::ProtoBuf.ProtoMember(2)]
        public V1 v1
        {
            get => __pbn__versions.Is(2) ? ((V1)__pbn__versions.Object) : default;
            set => __pbn__versions = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializev1() => __pbn__versions.Is(2);
        public void Resetv1() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__versions, 2);

        [global::ProtoBuf.ProtoContract()]
        public partial class V0 : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public Latest latest { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public global::System.Collections.Generic.List<Ranking> ranking { get; } = new global::System.Collections.Generic.List<Ranking>();

            [global::ProtoBuf.ProtoMember(3)]
            public int total_point { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Latest : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                [global::System.ComponentModel.DefaultValue("")]
                public string advertiser { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2)]
                public int point { get; set; }

                [global::ProtoBuf.ProtoMember(3)]
                [global::System.ComponentModel.DefaultValue("")]
                public string message
                {
                    get => __pbn__message ?? "";
                    set => __pbn__message = value;
                }
                public bool ShouldSerializemessage() => __pbn__message != null;
                public void Resetmessage() => __pbn__message = null;
                private string __pbn__message;

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Ranking : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                [global::System.ComponentModel.DefaultValue("")]
                public string advertiser { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2)]
                public int rank { get; set; }

                [global::ProtoBuf.ProtoMember(3)]
                [global::System.ComponentModel.DefaultValue("")]
                public string message
                {
                    get => __pbn__message ?? "";
                    set => __pbn__message = value;
                }
                public bool ShouldSerializemessage() => __pbn__message != null;
                public void Resetmessage() => __pbn__message = null;
                private string __pbn__message;

                [global::ProtoBuf.ProtoMember(4)]
                public int user_rank
                {
                    get => __pbn__user_rank.GetValueOrDefault();
                    set => __pbn__user_rank = value;
                }
                public bool ShouldSerializeuser_rank() => __pbn__user_rank != null;
                public void Resetuser_rank() => __pbn__user_rank = null;
                private int? __pbn__user_rank;

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class V1 : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public int total_ad_point { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue("")]
            public string message { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CommentLock : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            Unrestricted = 0,
            Locked = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CommentMode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Layout layout { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Layout
        {
            Normal = 0,
            SplitTop = 1,
            Background = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrialPanel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Panel panel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Mode unqualified_user { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Panel
        {
            Hidden = 0,
            Display = 1,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Mode
        {
            Allowed = 0,
            Restricted = 1,
            Forbidden = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProgramStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public State state { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum State
        {
            Unknown = 0,
            Ended = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TagUpdated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Tag> tags { get; } = new global::System.Collections.Generic.List<Tag>();

        [global::ProtoBuf.ProtoMember(2)]
        public bool owner_locked { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Tag : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string text { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            public bool locked { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            public bool reserved { get; set; }

            [global::ProtoBuf.ProtoMember(4)]
            [global::System.ComponentModel.DefaultValue("")]
            public string nicopedia_uri { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Statistics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long viewers
        {
            get => __pbn__viewers.GetValueOrDefault();
            set => __pbn__viewers = value;
        }
        public bool ShouldSerializeviewers() => __pbn__viewers != null;
        public void Resetviewers() => __pbn__viewers = null;
        private long? __pbn__viewers;

        [global::ProtoBuf.ProtoMember(2)]
        public long comments
        {
            get => __pbn__comments.GetValueOrDefault();
            set => __pbn__comments = value;
        }
        public bool ShouldSerializecomments() => __pbn__comments != null;
        public void Resetcomments() => __pbn__comments = null;
        private long? __pbn__comments;

        [global::ProtoBuf.ProtoMember(3)]
        public long ad_points
        {
            get => __pbn__ad_points.GetValueOrDefault();
            set => __pbn__ad_points = value;
        }
        public bool ShouldSerializead_points() => __pbn__ad_points != null;
        public void Resetad_points() => __pbn__ad_points = null;
        private long? __pbn__ad_points;

        [global::ProtoBuf.ProtoMember(4)]
        public long gift_points
        {
            get => __pbn__gift_points.GetValueOrDefault();
            set => __pbn__gift_points = value;
        }
        public bool ShouldSerializegift_points() => __pbn__gift_points != null;
        public void Resetgift_points() => __pbn__gift_points = null;
        private long? __pbn__gift_points;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Marquee : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Display display { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Display : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public OperatorComment operator_comment { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
            public global::System.TimeSpan? duration { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Enquete : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string question { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<Choice> choices { get; } = new global::System.Collections.Generic.List<Choice>();

        [global::ProtoBuf.ProtoMember(3)]
        public Status status { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Choice : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string description { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3)]
            public int per_mille
            {
                get => __pbn__per_mille.GetValueOrDefault();
                set => __pbn__per_mille = value;
            }
            public bool ShouldSerializeper_mille() => __pbn__per_mille != null;
            public void Resetper_mille() => __pbn__per_mille = null;
            private int? __pbn__per_mille;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Status
        {
            Closed = 0,
            Poll = 1,
            Result = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveOrder : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Jump jump
        {
            get => __pbn__to.Is(1) ? ((Jump)__pbn__to.Object) : default;
            set => __pbn__to = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializejump() => __pbn__to.Is(1);
        public void Resetjump() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__to, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__to;

        [global::ProtoBuf.ProtoMember(2)]
        public Redirect redirect
        {
            get => __pbn__to.Is(2) ? ((Redirect)__pbn__to.Object) : default;
            set => __pbn__to = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeredirect() => __pbn__to.Is(2);
        public void Resetredirect() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__to, 2);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
