// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: state.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dwango.nicolive.chat.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NicoliveState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Statistics statistics { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Enquete enquete { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public MoveOrder move_order { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Marquee marquee { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public CommentLock comment_lock { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public CommentMode comment_mode { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public TrialPanel trial_panel { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public ProgramStatus program_status { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public global::dwango.nicolive.chat.data.atoms.ModerationAnnouncement moderation_announcement { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
