// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: akashic.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dwango.nicolive.chat.data.atoms
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AkashicMessageEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string playId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public bool ignorable { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool transient { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::Google.Protobuf.WellKnownTypes.Struct parameters { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AkashicStateRouting : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long epoch { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<AkashicMessageEvent> join { get; } = new global::System.Collections.Generic.List<AkashicMessageEvent>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<AkashicMessageEvent> continuation { get; } = new global::System.Collections.Generic.List<AkashicMessageEvent>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<AkashicMessageEvent> shared { get; } = new global::System.Collections.Generic.List<AkashicMessageEvent>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
