// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cruise.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dwango.nicolive.chat.data.atoms
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CruiseRecentContents : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Content> items { get; } = new global::System.Collections.Generic.List<Content>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Content : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string contentId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue("")]
            public string title { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3)]
            [global::System.ComponentModel.DefaultValue("")]
            public string description { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4)]
            public Thumbnail thumbnails { get; set; }

            [global::ProtoBuf.ProtoMember(5)]
            public Period onAirTime { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            public Period showTime { get; set; }

            [global::ProtoBuf.ProtoMember(7)]
            public int viewers
            {
                get => __pbn__viewers.GetValueOrDefault();
                set => __pbn__viewers = value;
            }
            public bool ShouldSerializeviewers() => __pbn__viewers != null;
            public void Resetviewers() => __pbn__viewers = null;
            private int? __pbn__viewers;

            [global::ProtoBuf.ProtoMember(8)]
            public int comments
            {
                get => __pbn__comments.GetValueOrDefault();
                set => __pbn__comments = value;
            }
            public bool ShouldSerializecomments() => __pbn__comments != null;
            public void Resetcomments() => __pbn__comments = null;
            private int? __pbn__comments;

            [global::ProtoBuf.ProtoMember(9)]
            public ChannelOwner channel_owner
            {
                get => __pbn__content_owner.Is(9) ? ((ChannelOwner)__pbn__content_owner.Object) : default;
                set => __pbn__content_owner = new global::ProtoBuf.DiscriminatedUnionObject(9, value);
            }
            public bool ShouldSerializechannel_owner() => __pbn__content_owner.Is(9);
            public void Resetchannel_owner() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__content_owner, 9);

            private global::ProtoBuf.DiscriminatedUnionObject __pbn__content_owner;

            [global::ProtoBuf.ProtoMember(10)]
            public UserOwner user_owner
            {
                get => __pbn__content_owner.Is(10) ? ((UserOwner)__pbn__content_owner.Object) : default;
                set => __pbn__content_owner = new global::ProtoBuf.DiscriminatedUnionObject(10, value);
            }
            public bool ShouldSerializeuser_owner() => __pbn__content_owner.Is(10);
            public void Resetuser_owner() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__content_owner, 10);

            [global::ProtoBuf.ProtoContract()]
            public partial class Thumbnail : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                [global::System.ComponentModel.DefaultValue("")]
                public string listingThumbnailMiddle { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2)]
                [global::System.ComponentModel.DefaultValue("")]
                public string listingThumbnailLarge
                {
                    get => __pbn__listingThumbnailLarge ?? "";
                    set => __pbn__listingThumbnailLarge = value;
                }
                public bool ShouldSerializelistingThumbnailLarge() => __pbn__listingThumbnailLarge != null;
                public void ResetlistingThumbnailLarge() => __pbn__listingThumbnailLarge = null;
                private string __pbn__listingThumbnailLarge;

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Period : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
                public global::System.DateTime? beginAt { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
                public global::System.DateTime? endAt { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class ChannelOwner : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                [global::System.ComponentModel.DefaultValue("")]
                public string id { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2)]
                [global::System.ComponentModel.DefaultValue("")]
                public string name
                {
                    get => __pbn__name ?? "";
                    set => __pbn__name = value;
                }
                public bool ShouldSerializename() => __pbn__name != null;
                public void Resetname() => __pbn__name = null;
                private string __pbn__name;

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class UserOwner : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                [global::System.ComponentModel.DefaultValue("")]
                public string id { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2)]
                [global::System.ComponentModel.DefaultValue("")]
                public string name
                {
                    get => __pbn__name ?? "";
                    set => __pbn__name = value;
                }
                public bool ShouldSerializename() => __pbn__name != null;
                public void Resetname() => __pbn__name = null;
                private string __pbn__name;

            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
