// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: features.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dwango.nicolive.chat.data.atoms
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FeaturesUpdated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool audition_enabled
        {
            get => __pbn__audition_enabled.GetValueOrDefault();
            set => __pbn__audition_enabled = value;
        }
        public bool ShouldSerializeaudition_enabled() => __pbn__audition_enabled != null;
        public void Resetaudition_enabled() => __pbn__audition_enabled = null;
        private bool? __pbn__audition_enabled;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
