// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ichibalauncher.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dwango.nicolive.chat.data.atoms
{

    [global::ProtoBuf.ProtoContract()]
    public partial class IchibaLauncherItemSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long epoch { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<Item> items { get; } = new global::System.Collections.Generic.List<Item>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Item : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string id { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue("")]
            public string entityId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3)]
            [global::System.ComponentModel.DefaultValue("")]
            public string serviceName { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4)]
            [global::System.ComponentModel.DefaultValue("")]
            public string title { get; set; } = "";

            [global::ProtoBuf.ProtoMember(5)]
            public LaunchDialogType launchDialogType { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            [global::System.ComponentModel.DefaultValue("")]
            public string thumbnailUrl { get; set; } = "";

            [global::ProtoBuf.ProtoMember(7)]
            public int thumbnailWidth { get; set; }

            [global::ProtoBuf.ProtoMember(8)]
            public int thumbnailHeight { get; set; }

            [global::ProtoBuf.ProtoMember(9)]
            [global::System.ComponentModel.DefaultValue("")]
            public string launchUrl { get; set; } = "";

            [global::ProtoBuf.ProtoMember(10)]
            [global::System.ComponentModel.DefaultValue("")]
            public string addedUserId
            {
                get => __pbn__addedUserId ?? "";
                set => __pbn__addedUserId = value;
            }
            public bool ShouldSerializeaddedUserId() => __pbn__addedUserId != null;
            public void ResetaddedUserId() => __pbn__addedUserId = null;
            private string __pbn__addedUserId;

            [global::ProtoBuf.ProtoMember(11)]
            [global::System.ComponentModel.DefaultValue("")]
            public string reportUrl
            {
                get => __pbn__reportUrl ?? "";
                set => __pbn__reportUrl = value;
            }
            public bool ShouldSerializereportUrl() => __pbn__reportUrl != null;
            public void ResetreportUrl() => __pbn__reportUrl = null;
            private string __pbn__reportUrl;

            [global::ProtoBuf.ProtoMember(12)]
            public bool running { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum LaunchDialogType
            {
                SMALL = 0,
                RICHVIEW = 1,
            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
