// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: moderator.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dwango.nicolive.chat.data.atoms
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ModeratorUserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long user_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickname
        {
            get => __pbn__nickname ?? "";
            set => __pbn__nickname = value;
        }
        public bool ShouldSerializenickname() => __pbn__nickname != null;
        public void Resetnickname() => __pbn__nickname = null;
        private string __pbn__nickname;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string iconUrl
        {
            get => __pbn__iconUrl ?? "";
            set => __pbn__iconUrl = value;
        }
        public bool ShouldSerializeiconUrl() => __pbn__iconUrl != null;
        public void ReseticonUrl() => __pbn__iconUrl = null;
        private string __pbn__iconUrl;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModeratorUpdated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ModeratorOperation operation { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ModeratorUserInfo @operator { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? updatedAt { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ModeratorOperation
        {
            ADD = 0,
            DELETE = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SSNGUpdated : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public SSNGOperation operation { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long ssng_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ModeratorUserInfo @operator { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public SSNGType type
        {
            get => __pbn__type.GetValueOrDefault();
            set => __pbn__type = value;
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private SSNGType? __pbn__type;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string source
        {
            get => __pbn__source ?? "";
            set => __pbn__source = value;
        }
        public bool ShouldSerializesource() => __pbn__source != null;
        public void Resetsource() => __pbn__source = null;
        private string __pbn__source;

        [global::ProtoBuf.ProtoMember(6)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? updatedAt { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum SSNGOperation
        {
            ADD = 0,
            DELETE = 1,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum SSNGType
        {
            USER = 0,
            WORD = 1,
            COMMAND = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModerationAnnouncement : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string message
        {
            get => __pbn__message ?? "";
            set => __pbn__message = value;
        }
        public bool ShouldSerializemessage() => __pbn__message != null;
        public void Resetmessage() => __pbn__message = null;
        private string __pbn__message;

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public global::System.Collections.Generic.List<GuidelineItem> guidelineItems { get; } = new global::System.Collections.Generic.List<GuidelineItem>();

        [global::ProtoBuf.ProtoMember(3)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? updatedAt { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GuidelineItem
        {
            UNKNOWN = 0,
            SEXUAL = 1,
            SPAM = 2,
            SLANDER = 3,
            PERSONAL_INFORMATION = 4,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
