// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: notifications.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dwango.nicolive.chat.data.atoms
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SimpleNotificationV2 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NotificationType type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public bool show_in_telop { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool show_in_list { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum NotificationType
        {
            UNKNOWN = 0,
            ICHIBA = 1,
            EMOTION = 2,
            CRUISE = 3,
            PROGRAM_EXTENDED = 4,
            RANKING_IN = 5,
            VISITED = 6,
            SUPPORTER_REGISTERED = 7,
            USER_LEVEL_UP = 8,
            USER_FOLLOW = 9,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
